# Generated by Django 6.0.3 on 2026-03-06 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('total_analyses', models.IntegerField(default=0)),
                ('ai_detected', models.IntegerField(default=0)),
                ('human_detected', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_uploads/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.FloatField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('result', models.CharField(choices=[('human', 'Human Voice'), ('ai', 'AI Generated'), ('uncertain', 'Uncertain')], default='uncertain', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('spectral_score', models.FloatField(default=0.0)),
                ('pitch_score', models.FloatField(default=0.0)),
                ('rhythm_score', models.FloatField(default=0.0)),
                ('noise_score', models.FloatField(default=0.0)),
                ('formant_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
